# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EX_KMtA-t_pbahb9kypeedG5qSFhUix8
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Konfigurasi halaman
st.set_page_config(page_title="Bike Sharing Dashboard", layout="wide")

# Load data
df = pd.read_csv("main_data.csv")

# Judul dashboard
st.title("🚴‍♀️ Bike Sharing Dashboard")
st.markdown("Analisis peminjaman sepeda di Washington D.C. berdasarkan musim, hari kerja, cuaca, dan jenis pengguna.")

# Metrik ringkasan
col1, col2, col3 = st.columns(3)
col1.metric("Total Hari", df.shape[0])
col2.metric("Total Peminjaman", f"{df['cnt'].sum():,.0f}")
col3.metric("Rata-rata Harian", f"{df['cnt'].mean():.0f}")

st.markdown("---")

# Pilihan menu visualisasi
opsi = st.selectbox("Pilih Analisis", [
    "Distribusi Peminjaman",
    "Musim & Bulan",
    "Hari Kerja vs Libur",
    "Kondisi Cuaca",
    "Segmentasi Pengguna"
])

# Visualisasi berdasarkan pilihan
if opsi == "Distribusi Peminjaman":
    st.markdown("### Distribusi Jumlah Peminjaman Sepeda")
    fig, ax = plt.subplots()
    sns.histplot(df['cnt'], bins=30, kde=True, ax=ax)
    ax.set_title("Distribusi Jumlah Peminjaman Sepeda per Hari")
    st.pyplot(fig)

elif opsi == "Musim & Bulan":
    st.markdown("### Peminjaman Berdasarkan Musim")
    fig, ax = plt.subplots()
    sns.boxplot(x='season', y='cnt', data=df, palette='pastel', ax=ax)
    ax.set_title("Distribusi Peminjaman Berdasarkan Musim")
    st.pyplot(fig)

    st.markdown("### Rata-rata Peminjaman per Bulan")
    fig, ax = plt.subplots(figsize=(12, 4))
    order_m = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    sns.barplot(x='mnth', y='cnt', data=df, order=order_m, ci=None, palette='Set2', ax=ax)
    ax.set_title("Rata-Rata Jumlah Peminjaman per Bulan")
    st.pyplot(fig)

elif opsi == "Hari Kerja vs Libur":
    st.markdown("### Perbandingan Hari Kerja vs Libur")
    fig, ax = plt.subplots()
    sns.boxplot(x='workingday', y='cnt', data=df, palette='cool', ax=ax)
    ax.set_xticklabels(['Libur/Akhir Pekan', 'Hari Kerja'])
    ax.set_title("Peminjaman: Hari Kerja vs Libur")
    st.pyplot(fig)

elif opsi == "Kondisi Cuaca":
    st.markdown("### Pengaruh Cuaca terhadap Jumlah Peminjaman")
    weather_order = ['Clear or Partly Cloudy', 'Mist or Cloudy', 'Light Snow or Rain', 'Heavy Rain or Fog']
    fig, ax = plt.subplots()
    sns.boxplot(x='weathersit', y='cnt', data=df, order=weather_order, palette='coolwarm', ax=ax)
    ax.set_title("Pengaruh Cuaca terhadap Peminjaman")
    ax.set_xticklabels(weather_order, rotation=15)
    st.pyplot(fig)

elif opsi == "Segmentasi Pengguna":
    st.markdown("### Total Peminjaman Berdasarkan Jenis Pengguna")
    fig, ax = plt.subplots()
    sns.barplot(x=['casual', 'registered'], y=df[['casual', 'registered']].sum().values, palette='Set2', ax=ax)
    ax.set_ylabel("Total Peminjaman")
    ax.set_xlabel("Jenis Pengguna")
    ax.set_title("Total Peminjaman: Registered vs Casual")
    st.pyplot(fig)

    # Rata-rata bulanan per jenis pengguna
    st.markdown("### Rata-Rata Peminjaman Bulanan per Jenis Pengguna")
    # Pastikan mnth sudah dalam bentuk label
    month_order = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    df_month_user = df.groupby('mnth')[['casual', 'registered']].mean().reindex(month_order)
    fig, ax = plt.subplots(figsize=(12, 5))
    df_month_user.plot(kind='bar', ax=ax, color=['#9b59b6', '#3498db'])
    ax.set_title("Rata-Rata Bulanan: Casual vs Registered")
    ax.set_xlabel("Bulan")
    ax.set_ylabel("Jumlah Peminjaman")
    ax.legend(title="Jenis Pengguna")
    st.pyplot(fig)